### ISSUE TITLE
run_rr.py: No such file or directory

### ISSUE THREAD

**Issue by xiekunwhy** [AntonBankevich/LJA#6]
Hi,

I got error when run LJA "/Bio/Linux-src-files/NGS/Genome_assemblers/HiFI/LJA/bin/run_rr.py: No such file or directory" after about 1 day running.  run_rr.py not in bin directory but in py directory, no document to tell us how to install it in the right way.

Best,
Kun

**Comment by AntonBankevich** [comment]
Hi. This happened because you did not run "make install" after make as instructed in the installation manual. Though the fact that you had to find this out after most of the assembly process was finished is unfortunate and I will make sure to fix it. For now you can run make install to fix the problem. Also you can avoid repeating most of the calculations if you run the same lja command but with additional parameter --restart-from phase2.

**Comment by xiekunwhy** [comment]
Hi. Things worked, but you are forget to mention yaml module in the manual, And run_rr.py crashed again.
