### ISSUE TITLE
how to  decompress my select path from compressed.gfa

### ISSUE THREAD

**Issue by zhoudreames** [AntonBankevich/LJA#7]
![image](https://user-images.githubusercontent.com/54714639/138020615-5088adf8-958f-4be1-9396-4dc8b2397777.png)
I already know the best path from above graph，but how to decompress the path gfa files to gian origin sequence？
thank~

**Comment by AntonBankevich** [comment]
Hi. Unfortunately we currently do not provide uncompressed sequences of edges of the multiplex de Bruijn graph. It is technically difficult because uncompressing needs to be coordinated on overlaps between edge sequences. There are ways to avoid this issue, e.g. by providing imperfect overlaps between sequences in gfa. Alternatively we can provide a script that will run LJApolish module of LJA as a standalone tool but it is risky because LJApolish requires some extra information about read alignments that is generated by LJA. So, for now I can not help you, but I will implement one or both of these solutions in the next release (which should be very soon since a major bug was found) and get back to you.
